import BlogList from '@/app/components/BlogList'
import React from 'react'

export const metadata = {
  description: 'Generated by create next app',
  title: 'About',
}
export default function Page() {
  return (
    <div className='h-screen text-3xl text-white flex mt-20'>
        <BlogList />
    </div>
  )
}
