import React from 'react'
export const metadata = {
    title: 'Setting',
    description: 'Generated by create next app',
  }
export default function Page() {
  return (
    <div className='h-screen text-3xl text-white flex items-center justify-center '>
      this is the app Setting
    </div>
  )
}
