import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,teams,analytics }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
           <div className="w-screen mx-auto">
            <div className="flex justify-center gap-4 p-4 text-blue-400">
              <Link href="/">Home</Link>
              <Link href="/about">About</Link>
            </div>
            <div className="flex gap-6">
              {teams}
              {analytics}
            </div>
            {children}
           </div>
        </AntdRegistry>
      </body>
    </html>
  );
}
