import React from 'react'

export const metadata = {
  title: 'Me',
  description: 'Generated by create next app',
}
export default function Page() {
  return (
    <div className='h-screen text-3xl text-white flex items-center justify-center '>
      About Me
    </div>
  )
}
